class CameraCapture:
    def __init__(self, camera_index=0):
        ...

    def start(self) -> None:
        ...

    def _capture_loop(self) -> None:
        ...

    def get_latest_frame(...) -> FrameData | None:
        ...

    def get_statistics(self) -> dict:
        ...

    def stop(self) -> None:
        ...